# Investigation of numpy.random package

Submitted as part of the requirements for the GMIT Higher Diploma in Data Analysis as part of the module Programme for Data Analysis 2019

![JupyterSymbols](img/Header%20Image.png)

#### Table of Contents: 
- Introduction to Numpy
- Section 1: Explain the use of the overall purpose of the numpy.random package 
- Section 2: Explain the use of "Single Random Data" and "Premutations" functions
- Section 3: Explain the use and purpose of a least five "Distributions" functions
                    #### Function 1
                    #### Function 2
                    #### Function 3
                    #### Function 4
                    #### Function 5
- Section 4: Explain the use of seeds in generating pseudorandom numbers
- References

##### Note: Throughout the notebook, the numpy package (import numpy as py) is called in each section to ensure the notebook and its explainations are accessible to the users. 

## Introduction to Numpy

NumPy (Numerical Python) is an open source add on package to Python. The overall purpose of the package is to provide mathematical and numerical routines through precompiled fast functions [(1)](#ref1). Developed in the 2000's, NumPy is seen as a fundamental computing package crucial for data analysis and machine learning objects due to its efficiency and ability to interface with other packages within the Python library such as pandas and matplotlib.  

The NumPy package proivdes
 - "homogenous multidimensional arrays"(2),
 - outputed through various derived objects (matrices and vectors) and,
 - numerous computations for fast operations on the aforementioned arrays (random selections, shape manipulation, statistical operations) (3). 
 
These arrays can be accessed and manipulated similiarly to the list function and must be of one data type i.e. integer, string etc.

## Section 1: Purpose of numpy.random package

The numpy.random package is a function within the NumPy package for doing random sampling computations that returns arrays of specified shapes and sizes. The following section will outline key functions with the numpy.random package as outlined on the NumPy documentation on Scipy.org (4) [Version 1.15](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html).

#### The sections of the numpy.random package are: 

<table>
  <tr>
    <th style="border:1px solid; text-align:center">Sections </th>
    <th style="border:1px solid; text-align:center">No of Functions </th>
    <th style="border:1px solid ; text-align:center">Brief Descriptions </th>
  </tr>
  <tr>
    <td style="border:1px solid; text-align:center">Random Sample Data </td>
    <td style="border:1px solid; text-align:center">10 functions</td>
    <td style="border:1px solid ; text-align:center">Random data computations on specified arrays</td>
  </tr>
  <tr>
    <td style="border:1px solid; text-align:center">Permutations</td>
    <td style="border:1px solid; text-align:center">2 functions</td>
    <td style="border:1px solid ; text-align:center">Alters the sequence of generated outputs within arrays</td>
  </tr>
  <tr>
    <td style="border:1px solid; text-align:center">Distributions</td>
    <td style="border:1px solid; text-align:center">35 functions</td>
    <td style="border:1px solid ; text-align:center">Determines the occurance of variables accross defined parameters within arrays</td>
  </tr>
  <tr>
    <td style="border:1px solid; text-align:center">Random Generator</td>
    <td style="border:1px solid; text-align:center">4 functions </td>
    <td style="border:1px solid; text-align:center">Determining the probability of occurance within arrays</td>
  </tr>
</table>

|Sections |No of Functions |Brief Descriptions |
|:-:|:-:|:-:| 
|Random Sample Data | 10 functions |Random data computations on specified arrays
|Permutations | 2 functions | Alters the sequence of generated outputs within arrays
|Distributions |35 functions |Determines the occurance of variables accross defined parameters within arrays
|Random Generator | 4 functions | Determining the probability of occurance within arrays

#### Importing the NumPy Package

To begin working with the NumPy Package, it first has to be installed. In this notebook, the Numpy Package was imported throught the Anaconda package.

In [2]:
import numpy as np # importing the package for use in the notebook

## Section 2: Explanation of Functions
### (a) Simple Random Data

The Simple Random Data within Numpy is a range of precompiled computations that will generate random numbers of the same types that is held within arrays. This arrays are usually drawn from "commonly used distributions:Uniform, Normal (Gaussian), Binomial and Poission"(5). 

There are 10 functions within the Simple Random Data Function list below.

- _**rand**_
- randn
- _**randint**_
- random integers
- random_sample([size])	Return random floats in the half-open interval [0.0, 1.0).
- random([size])	Return random floats in the half-open interval [0.0, 1.0).
- ranf([size])	Return random floats in the half-open interval [0.0, 1.0).
- sample([size])	Return random floats in the half-open interval [0.0, 1.0).
- choice(a[, size, replace, p])	Generates a random sample from a given 1-D array
- bytes(length)	Return random bytes.

This notebook will explore a sample of the functions to explain the purpose and capabilities of the package and its uses within Data Analysis. The outputs will be returned in ndarrays. This are indicated in bold and italics. 
The size, type and structure of the ndarray will be determined by function called. 

#### random.rand ()
Use of the random function in NumPy, returns positive random generated integer.

**Type of array** To determine the type of array for any function, call the type (np.random.rand()) function

In [3]:
np.random.rand() # All numbers generated within the normal distribution. The return is a float number

0.9039170840185463

In [33]:
type(np.random.rand())# This function will call the type of data that you are working with

float

In [4]:
np.random.rand(3) # The numbers of instances of the function is set by the parameters in the brackets. 
#This function will return 3 instances of a random generated number. It is displayed in a vector or a 1 dimensional array.

array([0.38848828, 0.39056973, 0.47573089])

#### random.randint ()
Within the random.randint function, the output are whole integers rather than floats. This function enables users to set the parameters of the output from low to high, 1 and 5. 

*Shape of Output:* This is determined the the amount of axes outlined in the size (). The first number refers to the number of rows and the second refers to the columns that will be generated. 

In [34]:
np.random.randint(2, 5, size=(2, 4)) # This is a 2 dimensional array denoted by the size () parameters. 
# The range in which the outputs are generated from are between 0,5.

array([[4, 3, 3, 2],
       [3, 3, 4, 3]])

In addition, this function will determine parameters if the higher range is not defined. The function accepts the integer inputted as the high parameter. 

In [32]:
np.random.randint(6, size=(2, 2 ,2, 2)) # This multidimensional array returns 2 rows, 2 columns, 2 groups and 2 sections.    

array([[[[0, 2],
         [0, 3]],

        [[1, 0],
         [1, 3]]],


       [[[3, 1],
         [5, 1]],

        [[1, 3],
         [2, 1]]]])

In [12]:
np.random.randint(6, size=10) 

array([2, 1, 0, 3, 1, 5, 4, 0, 3, 4])

In [13]:
print(np.arange(0, 10))

[0 1 2 3 4 5 6 7 8 9]


In [14]:
# Lower limit is 0 be default
print(np.arange(5))  

# 0 to 9
print(np.arange(0, 10))  

# 0 to 9 with step of 2
print(np.arange(0, 10, 2))  

# 10 to 1, decreasing order
print(np.arange(10, 0, -1))

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]


### (b) Permutations

Within the numpy.random package there are two main permutations packages: 

Shuffle:     Within a 1 dimensional array, this function will change the order of all the contents
             Within a multidimensional array, this function will rearrange the contents of the whole array within the defined    parameters
         
Permutation: Within a 1 dimensional array, this function will change the order of the contents
             Within a mulitdimensional array, this function will keep the contents of a defined parameter e.g. axes but rearrange the contacts within that axes. (5)
            

In [15]:
arr = np.arange(10) # An array of numbers within the range 10
np.random.shuffle(arr) # Arr is given a value to prepare for use of shuffle function
arr

array([0, 4, 3, 7, 8, 6, 5, 2, 1, 9])

In [16]:
np.arange(9).reshape((3, 3)) # 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
np.random.permutation(10)

array([9, 6, 3, 7, 4, 8, 5, 1, 2, 0])

In [18]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
my_list = [1, 2, 3, 4, 5] 
my_numpy_list = np.array(my_list)
my_numpy_list  #This line show the result of the array generated

array([1, 2, 3, 4, 5])

In [20]:
second_list = [[1,2,3], [5,4,1], [3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr  #This line show the result of the array generated

array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
arr1 = 3
arr2 = 2
np.add(arr1,arr2)

5

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.random.randint(2, size=10)

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 1])

In [25]:
np.random.random_sample()

0.012940751013852725

In [26]:
type(np.random.random_sample())

float

In [27]:
np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 3, 3], dtype=int64)

## Section 3: Distributions in numpy.random packages

#### Binomial Distribution

For a variable to be a binomial random variable, ALL of the following conditions must be met:

There are a fixed number of trials (a fixed sample size).
On each trial, the event of interest either occurs or does not.
The probability of occurrence (or not) is the same on each trial.
Trials are independent of one another.

In [28]:
import numpy as np
n = 10
p = 0.5
np.random.binomial(n, p, 1000)
sum(np.random.binomial(n, p, 2) == 0)/1

0.0

In [29]:
probs_100 = [np.equal(x,i).mean() for i in range(n)]
print(probs_100)

NameError: name 'x' is not defined

https://towardsdatascience.com/fun-with-the-binomial-distribution-96a5ecabf65b

In [ ]:
# Import libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Input variables
# Number of trials
trials = 1000
# Number of independent experiments in each trial
n = 10
# Probability of success for each experiment
p = 0.5
# Function that runs our coin toss trials
# heads is a list of the number of successes from each trial of n experiments
def run_binom(trials, n, p):
    heads = []
    for i in range(trials):
        tosses = [np.random.random() for i in range(n)]
        heads.append(len([i for i in tosses if i>=0.50]))
    return heads
# Run the function
heads = run_binom(trials, n, p)
# Plot the results as a histogram
fig, ax = plt.subplots(figsize=(14,7))
ax = sns.distplot(heads, bins=11, label='simulation results')
ax.set_xlabel("Number of Heads",fontsize=16)
ax.set_ylabel("Frequency",fontsize=16)
plt.show()a

https://cmdlinetips.com/2018/12/simulating-coin-toss-experiment-with-binomial-random-numbers-using-numpy/

In [ ]:

probs_100 = [np.equal(x,i).mean() for i in range(n)]
print(probs_100)
plt.xticks(range(n))
plt.plot(list(range(n)), probs_100, color='blue', marker='o')
plt.xlabel('Number of Heads',fontsize=14)
plt.ylabel('Probability',fontsize=14)

In [ ]:
n, p = 10, .5
s = np.random.binomial(n, p, 5)
print (s)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x = np.random.uniform(0.0, 10.0, 100)
y = np.random.uniform(0.0, 100.0, 100)
z = np.random.normal(100.0, 40.0, 100)
c = np.random.randint(0, 20, 100)

plt.scatter(x, y, c=c, s=z)

plt.show()

#Ian's Git Hub

In [ ]:
#Ian's Git Hub
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(0.0, 10.0, 0.01)
y = 3.0 * x + 1.0
noise = np.random.normal(0.0, 1.0, len(x))

plt.plot(x, y + noise, 'r.', label="Actual")
plt.plot(x, y, 'b-', label="Model")

plt.title("Simple plot")
plt.xlabel("Weight")
plt.ylabel("Mass")
plt.legend()

plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

plt.subplot(1, 2, 1)
x = np.random.normal(0.0, 1.0, 10000)
plt.hist(x)

plt.subplot(1, 2, 2)
x = np.random.uniform(-3.0, 3.0, 10000)
plt.hist(x)

plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(2.0, 50.0, 0.5)

plt.plot(x, x**2, 'g-', label="x^2")
plt.plot(x, x**3, 'b-', label="x^3")
plt.plot(x, x**4, 'r-', label="x^4")
plt.plot(x, 2**x, 'k-', label="2^x")

plt.legend()

plt.show()

#Ian's git Hub

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(-2.0 * np.pi, 2.0 * np.pi, 0.1)

plt.plot(x, np.sin(x), 'g.')
plt.plot(x, np.cos(x), 'b.')

plt.show()
#Ian's Git Hub

#### Chisquare Distribution

#### Exponential Distribution

#### Uniform Distribution

Within ths distribution, samples are returned from a half open interval meaning the the lower paramenter is included while the higher one is not. Each value within the interval is equally likely to be drawn. There will be no part of the return that will have more outputs than the rest. 

https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.uniform.html#numpy.random.uniform

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
arr = np.random.rand (10000)
print (arr)

In [ ]:
plt.hist(arr)

## Section 4: Explain the use of seeds in generating pseudorandom numbers

Pseudorandom numbers within the NumPy package refer to the deterministic methods used to generate seemingly random numbers. These are known as Psudeorandom Number Generators (PRNGs). PRNG are common amongst programming librarys. NumPy PRNG uses the Merseen Twister to generate random numbers within functions. 

Within the random function, the starting point is different everytime the function is called, so is the output even though the algorithm used is the same. This is useful within Data Analysis when you want to generate the same output each time the function is called. As the algorithm is the same, uses within cryptography are limited as the seed can easily be indentified. 

The seed function is called using the numpy.random.seed function, setting the starting point as the same for each time the funciton is called leading to the same data being generated.

Within the below example, the seed is not set, therefore the starting point of the the function is different every time. 

In [ ]:
import numpy as np
np.random.rand(4)

To demonstrate the randomn numbers generated because there is no seed set when called.

In [ ]:
np.random.rand(4)

The function np.random.seed has been called for the following two functions, this wil demontrate that the seed functions sets the initial starting point of the algorithms, resulting with the same output

In [ ]:
np.random.seed(0) ; np.random.rand(4)

And lets try that again to see what numbers are generated.

In [ ]:
np.random.seed(0) ; np.random.rand(4)

## References: 
 1. https://sites.engineering.ucsb.edu/~shell/che210d/numpy.pdf<a id='#ref1'></a>
 2. https://docs.scipy.org/doc/numpy/user/quickstart.html
 3. https://pynative.com/python-random-module/
 4. https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html
 5. https://www.ntu.edu.sg/home/ehchua/programming/webprogramming/Python4_DataAnalysis.html
 6. http://hamelg.blogspot.com/2015/11/python-for-data-analysis-part-8-numpy.html
 
(Section 3) http://hplgit.github.io/primer.html/doc/pub/random/._random-solarized001.html

Binomial References: 
https://www.geeksforgeeks.org/binomial-random-variables/
https://www.pluralsight.com/guides/almost-random-numbers
https://www.pluralsight.com/guides/almost-random-numbers
https://stackoverflow.com/questions/27644617/difference-between-n-and-size-parameters-in-np-random-binomialn-p-size-1000
https://discuss.codecademy.com/t/what-does-the-np-random-binomial-function-return/361162
https://www.statisticshowto.datasciencecentral.com/probability-and-statistics/binomial-theorem/binomial-distribution-formula/

 (Section 4) https://www.sicara.ai/blog/2019-01-28-how-computer-generate-random-numbers
             https://www.pluralsight.com/guides/almost-random-numbers
             https://www.geeksforgeeks.org/pseudo-random-number-generator-prng/
             https://stackoverflow.com/questions/21494489/what-does-numpy-random-seed0-do
             https://machinelearningmastery.com/how-to-generate-random-numbers-in-python/
