# Investigation of numpy.random package

### Programme for Data Analysis 2019

# Table of Contents:
#### Introduction to Numpy
#### Section 1: Explain the use of the overall purpose of the numpy.random package 
#### Section 2: Explain the use of "Single Random Data" and "Premutations" functions
#### Section 3: Explain the use and purpose of a least five "Distributions" functions
                    #### Function 1
                    #### Function 2
                    #### Function 3
                    #### Function 4
                    #### Function 5
####  Section 4: Explain the use of seeds in generating pseudorandom numbers
#### References

## Introduction to Numpy

### NumPy (Numerical Python) is an open source add on to Python. The main purpose of the package is to provides mathematical and numerical routines in precompiled fast functions (1). Developed in the 2000's, NumPy is seen as a fundemental package crucial for data analysis and machine learning objects as it is efficienct and interfaces with other packages such as pandas.  

### NumPy's  is a Python library that proivdes a "homogenous multidimensional array" (2), varios derived objects (matrices) and numerous computations for fast operations on the aforementioned arrays (random selections, shape manipulation, statistical operations) (3).  These array can be accessed and manipulated similiarly to the list function and must be of one data type i.e. integer, string. 

## Section 1: Purpose of numpy.random package

import numpy as np
np.random.rand(1,2)

In [10]:
my_list = [1, 2, 3, 4, 5]
my_numpy_list = np.array(my_list)
my_numpy_list  #This line show the result of the array generated

array([1, 2, 3, 4, 5])

In [11]:
second_list = [[1,2,3], [5,4,1], [3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr  #This line show the result of the array generated

array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
arr1 = 3
arr2 = 2
np.add(arr1,arr2)

5

## Section 2: Explanation of Functions
### (a) Simple Random Data

### (b) Permutations

## Section 3: Distributions in numpy.random packages

## References: 
### 1. https://sites.engineering.ucsb.edu/~shell/che210d/numpy.pdf
### 2. https://docs.scipy.org/doc/numpy/user/quickstart.html

# 1). https://numpy.org/
# 2). https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html