# Investigation of numpy.random package

### Programme for Data Analysis 2019

## Background to the Numpy Package

#### Numpy (Numerical Python) is the fundamental package for scientific computing within Python (1).# Numpy's It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.# (2)
#### The notebook using the numpy.random package will: 
#### - Explain the use of the overall purpose of the numpy.random package 
#### - Explain the use of "Single Random Data" and "Premutations" functions
#### - Explain the use and purpose of a least five "Distributions" functions
                    #### Function 1
                    #### Function 2
                    #### Function 3
                    #### Function 4
                    #### Function 5
#### - Explain the use of seeds in generating pseudorandom numbers

## Section 1: Purpose of numpy.random package

import numpy as np
np.random.rand(1,2)

In [10]:
my_list = [1, 2, 3, 4, 5]
my_numpy_list = np.array(my_list)
my_numpy_list  #This line show the result of the array generated

array([1, 2, 3, 4, 5])

In [11]:
second_list = [[1,2,3], [5,4,1], [3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr  #This line show the result of the array generated

array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
arr1 = 3
arr2 = 2
np.add(arr1,arr2)

5

## References: 

# 1). https://numpy.org/
# 2). https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html