# Investigation of numpy.random package

### Programme for Data Analysis 2019

# Table of Contents: - image needed
#### Introduction to Numpy
#### Section 1: Explain the use of the overall purpose of the numpy.random package 
#### Section 2: Explain the use of "Single Random Data" and "Premutations" functions
#### Section 3: Explain the use and purpose of a least five "Distributions" functions
                    #### Function 1
                    #### Function 2
                    #### Function 3
                    #### Function 4
                    #### Function 5
####  Section 4: Explain the use of seeds in generating pseudorandom numbers
#### References

## Introduction to Numpy

NumPy (Numerical Python) is an open source add on to Python. The main purpose of the package is to provides mathematical and numerical routines in precompiled fast functions (1). Developed in the 2000's, NumPy is seen as a fundemental package crucial for data analysis and machine learning objects as it is efficienct and interfaces with other packages such as pandas.  

NumPy's  is a Python library that proivdes a "homogenous multidimensional array" (2), various derived objects (matrices) and numerous computations for fast operations on the aforementioned arrays (random selections, shape manipulation, statistical operations) (3).  These array can be accessed and manipulated similiarly to the list function and must be of one data type i.e. integer, string. 

## Section 1: Purpose of numpy.random package

The numpy.random package is a function in NumPy for doing random sampling returning arrays of specified shapes and sizes. The following section will outline key functions with the numpy.random package as outlined on the NumPy documentation on Scipy.org (4) Version 1.16.

#### Importing the NumPy Package

In [3]:
import numpy as np

#### Use of the random function in NumPy, returns a single positive random generated integer. This will return a 1 dimensional array.

In [4]:
np.random.rand() # All numbers generated within the normal distribution

0.8176258112477195

#### Returns an array of a defined shape containing positive random generated integers. This will return a 2 dimensional array.

In [5]:
np.random.random_sample((3,2)) # The brackets indicate the shape of the returned array. In this instance 3 rows and 2 columns.

array([[0.78882005, 0.29065708],
       [0.83269274, 0.65074552],
       [0.68833632, 0.92009804]])

In [6]:
np.random.rand(2, 2 ,2, 2) # 3D Array   

array([[[[0.00340154, 0.96887293],
         [0.43215389, 0.99088094]],

        [[0.13406976, 0.59421331],
         [0.47424252, 0.17649986]]],


       [[[0.67866101, 0.63188735],
         [0.2406943 , 0.42596123]],

        [[0.63322434, 0.02889347],
         [0.07726482, 0.25604414]]]])

In [7]:
np.random.randint(5, size=(2, 4)) # Parameters explaination needed

array([[0, 3, 0, 0],
       [1, 4, 2, 3]])

#### Section 2

In [8]:
my_list = [1, 2, 3, 4, 5] 
my_numpy_list = np.array(my_list)
my_numpy_list  #This line show the result of the array generated

array([1, 2, 3, 4, 5])

In [9]:
second_list = [[1,2,3], [5,4,1], [3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr  #This line show the result of the array generated

array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
arr1 = 3
arr2 = 2
np.add(arr1,arr2)

5

## Section 2: Explanation of Functions
### (a) Simple Random Data

In [13]:
import numpy as np - add in note about numpy being imported twice
np.random.rand(3,2)

array([[0.71265134, 0.44252942],
       [0.46701576, 0.68463267],
       [0.87931313, 0.4110768 ]])

In [14]:
np.random.randint(2, size=10)

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 1])

In [16]:
np.random.random_sample()

0.5581501312723536

In [15]:
type(np.random.random_sample())

float

In [17]:
np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 2, 3], dtype=int64)

### (b) Permutations

## Section 3: Distributions in numpy.random packages

## References: 
### 1. https://sites.engineering.ucsb.edu/~shell/che210d/numpy.pdf
### 2. https://docs.scipy.org/doc/numpy/user/quickstart.html
### 3. https://pynative.com/python-random-module/
### 4.https://docs.scipy.org/doc/numpy-1.16.0/reference/routines.random.html#

# 1). https://numpy.org/
# 2). https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html