# Investigation of numpy.random package

### Programme for Data Analysis 2019

# Table of Contents: - image needed
#### Introduction to Numpy
#### Section 1: Explain the use of the overall purpose of the numpy.random package 
#### Section 2: Explain the use of "Single Random Data" and "Premutations" functions
#### Section 3: Explain the use and purpose of a least five "Distributions" functions
                    #### Function 1
                    #### Function 2
                    #### Function 3
                    #### Function 4
                    #### Function 5
####  Section 4: Explain the use of seeds in generating pseudorandom numbers
#### References

##### Note: Throughout the notebook, the numpy package is called to ensure the notebook and its eplainations are accessible to the users. 

## Introduction to Numpy

NumPy (Numerical Python) is an open source add on to Python. The main purpose of the package is to provides mathematical and numerical routines in precompiled fast functions (1). Developed in the 2000's, NumPy is seen as a fundemental package crucial for data analysis and machine learning objects as it is efficienct and interfaces with other packages such as pandas.  

NumPy's  is a Python library that proivdes a "homogenous multidimensional array" (2), various derived objects (matrices) and numerous computations for fast operations on the aforementioned arrays (random selections, shape manipulation, statistical operations) (3).  These array can be accessed and manipulated similiarly to the list function and must be of one data type i.e. integer, string. 

## Section 1: Purpose of numpy.random package

The numpy.random package is a function in NumPy for doing random sampling returning arrays of specified shapes and sizes. The following section will outline key functions with the numpy.random package as outlined on the NumPy documentation on Scipy.org (4) Version 1.15.(Link to notebook).

The outputs within this package are mainly numerical and can be One dimensional or Multidimensional arrays as demonstrated below. 

#### Importing the NumPy Package

In [62]:
import numpy as np

## Section 2: Explanation of Functions
### (a) Simple Random Data

The Simple Random Data with Numpy is a range of precompiled computations that will generate random numbers of the same types that is held within arrays. This arrays are usually drawn from "commonly used distributions:Uniform, Normal (Gaussian), Binomial and Poission"(5). 

#### Use of the random function in NumPy, returns a single positive random generated integer. This will return a 1 dimensional array.

In [63]:
np.random.rand() # All numbers generated within the normal distribution

0.27608678478089943

#### Returns an array of a defined shape containing positive random generated integers. This will return a 2 dimensional array.

In [64]:
np.random.random_sample((3,2)) # The brackets indicate the shape of the returned array. In this instance 3 rows and 2 columns.

array([[0.74513217, 0.69248056],
       [0.95569335, 0.22316183],
       [0.29260005, 0.6984574 ]])

In [65]:
np.random.rand(2, 2 ,2, 2) # 3D Array   

array([[[[0.82187209, 0.70887579],
         [0.01357701, 0.36267807]],

        [[0.83768565, 0.86091347],
         [0.80795417, 0.20249112]]],


       [[[0.0571955 , 0.37945715],
         [0.70402407, 0.17214994]],

        [[0.74501803, 0.09438191],
         [0.09472554, 0.04356842]]]])

In [66]:
np.random.randint(5, size=(2, 4)) # Parameters explaination needed

array([[3, 0, 3, 3],
       [1, 3, 2, 0]])

## Section 2: Explanation of Functions
### (a) Simple Random Data

The Simple Random Data with Numpy is a range of precompiled computations that will generate random numbers of the same types that is held within arrays. This arrays are usually drawn from "commonly used distributions:Uniform, Normal (Gaussian), Binomial and Poission"(5). 

The random.random_sample function returns the type of outputs that is being generated by the function. 

In [67]:
import numpy as np
type(np.random.random_sample())

float

The random.rand function will generate integers within predefined parameters. The amount of results and the shape of the array is defined within the brackets following the function being called. 

In [68]:
np.random.rand(3,2)

array([[0.89594401, 0.27924692],
       [0.75579427, 0.84237962],
       [0.43318777, 0.35980495]])

Within the random.randint function, the output are whole integers rather than floats. This function enables users to set the parameters of the output from low to high, 1 and 5. The size of the function is determined by the folloowing bracketed numbers in the main brackets, 2 and 4). The results is a 2 Dimensional Matrix with 2 rows and foul columns with each of the outputs between the parameters of 1 and 5.

In [69]:
np.random.randint(1, 5, (2,4)) 

array([[4, 3, 1, 4],
       [4, 3, 2, 3]])

In addition, this function will determine parameters if the higher range is not defined. The function accepts the integer inputted as the high parameter. 

In [70]:
np.random.randint(6, size=10) 

array([1, 0, 0, 0, 5, 0, 5, 5, 1, 4])

### (b) Permutations

Within the numpy.random package there are two main permutations packages: 

Shuffle:     Within a 1 dimensional array, this function will change the order of all the contents
             Within a multidimensional array, this function will rearrange the contents of the whole array within the defined    parameters
         
Permutation: Within a 1 dimensional array, this function will change the order of the contents
             Within a mulitdimensional array, this function will keep the contents of a defined parameter e.g. axes but rearrange the contacts within that axes. (5)
            

In [90]:
arr = np.arange(10) # An array of numbers within the range 10
np.random.shuffle(arr) # Arr is given a value to prepare for use of shuffle function
arr

array([6, 7, 4, 1, 0, 9, 3, 2, 5, 8])

In [73]:
np.arange(9).reshape((3, 3)) # 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [74]:
np.random.permutation(10)

array([1, 9, 2, 7, 8, 0, 4, 3, 6, 5])

In [75]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
my_list = [1, 2, 3, 4, 5] 
my_numpy_list = np.array(my_list)
my_numpy_list  #This line show the result of the array generated

array([1, 2, 3, 4, 5])

In [77]:
second_list = [[1,2,3], [5,4,1], [3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr  #This line show the result of the array generated

array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

In [78]:
np.zeros(3)

array([0., 0., 0.])

In [79]:
arr1 = 3
arr2 = 2
np.add(arr1,arr2)

5

In [80]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
np.random.randint(2, size=10)

array([0, 1, 0, 1, 0, 1, 1, 0, 0, 0])

In [82]:
np.random.random_sample()

0.1947000306353519

In [83]:
type(np.random.random_sample())

float

In [84]:
np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 3, 2], dtype=int64)

### (b) Permutations

## Section 3: Distributions in numpy.random packages

## References: 
 1. https://sites.engineering.ucsb.edu/~shell/che210d/numpy.pdf
 2. https://docs.scipy.org/doc/numpy/user/quickstart.html
 3. https://pynative.com/python-random-module/
 4. https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html
 5. https://www.ntu.edu.sg/home/ehchua/programming/webprogramming/Python4_DataAnalysis.html
