# Investigation of numpy.random package

## Programme for Data Analysis 2019

### Overview of Jupyter Notebook

#### Section 1: Purpose of numpy.random package

In [9]:
import numpy as np
np.random.rand(1,2)

array([[0.58759022, 0.04716132]])

In [10]:
my_list = [1, 2, 3, 4, 5]
my_numpy_list = np.array(my_list)
my_numpy_list  #This line show the result of the array generated

array([1, 2, 3, 4, 5])

In [11]:
second_list = [[1,2,3], [5,4,1], [3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr  #This line show the result of the array generated

array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
arr1 = 3
arr2 = 2
np.add(arr1,arr2)

5